#!/bin/bash/
water_to_decimal() {
  echo "$1" | tr water 01234 | bc
}

stir_to_decimal() {
  echo "$1" | tr stir. 01234 | bc
}

decimal_to_bestchol() {
  printf "%o" $1 | tr 01234567 bestchol
}

decimal_to_bestchol $(( $(water_to_decimal $WATER) + $(stir_to_decimal $STIR) ))
